import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import Header from "@/components/Header";
import "./globals.css";
import DotGrid from "@/components/DotGrid";
import Footer from "@/components/Footer";

const firaCode = Fira_Code({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={firaCode.className}>
      <body
        className={`antialiased min-h-screen`}
      >
        <div className="fixed inset-0 -z-10 bg-black">
          <DotGrid
            dotSize={3}
            gap={60}
            baseColor="#1B3B17"
            activeColor="#01FE2B"
            proximity={120}
            shockRadius={200}
            shockStrength={3}
            resistance={750}
            returnDuration={1.5}
          />
        </div>
        
        <div className="relative z-10">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}